### ISSUE TITLE
Can't decode "WorkbookError"

### ISSUE THREAD

**Issue by mschnell1** [MortalreminderPT/edit-xlsx#16]
As it is in the `results `module, which is private. 

I simply want to decently print the "file not found error" by
```
            let e_text = match e {
                edit_xlsx::result::WorkbookError::FileNotFound  => "File not Found: ".to_owned() + &format!("{:?}", in_file_name),
                _ => format!("{:?}", e),
            };
```

**Comment by MortalreminderPT** [comment]
The fact is that Error is not very functional right now.
I was going to refactor it after I finished the documentation, but that's been put on hold for a number of reasons

**Comment by mschnell1** [comment]
I perfectly get a "File Not Found" error  with ` Workbook::from_path(in_file_name)`
I can display it  correctly decode by  `format!("{:?}", e)` with e from the result, and hence a WorkbookError.
I in fact don't understand how the debug print functionality can get that information to be displayed from the private error type. 
In the end I would like to just do `Workbook::from_path(in_file_name)?`, but the result type of my function is `std::io::Errror` and this is not compiled as not converter function is found.

**Comment by MortalreminderPT** [comment]
I implemented it in a new commit, you can see the way to convert a custom Error by clicking [here](https://github.com/MortalreminderPT/edit-xlsx/blob/36583a0edcb222123ea36aa8b2e091a9bc44a806/tests/test_error.rs#L7) 😊

**Comment by mschnell1** [comment]
Sorry, but I still can't find out how to `use `the word `WorkbookError ` ( defined in `results.rs`) in my code. 
That is why I cant compile your snippet. 

If I do `use edit_xlsx::WorkbookError; ` I get  `no `WorkbookError` in the root`

**Comment by mschnell1** [comment]
@MortalreminderPT 

Ooops. 
Now trying to recompile I get 

```
  --> C:\Users\mschnell\.cargo\registry\src\index.crates.io-6f17d22bba15001f\edit-xlsx-0.4.4\src\result.rs:35:5
   |
34 |     ColError(ColError),result
   |                              -
   |                              |
   |                              expected one of `(`, `,`, `=`, `{`, or `}`
   |                              help: missing `,`
35 |     DuplicatedSheets,
   |     ^^^^^^^^^^^^^^^^ unexpected token
```

**Comment by MortalreminderPT** [comment]
> @MortalreminderPT 
> 
> Ooops. 
> Now trying to `cargo clean` and recompile I get 
> 
> ```
>   --> C:\Users\mschnell\.cargo\registry\src\index.crates.io-6f17d22bba15001f\edit-xlsx-0.4.4\src\result.rs:35:5
>    |
> 34 |     ColError(ColError),result
>    |                              -
>    |                              |
>    |                              expected one of `(`, `,`, `=`, `{`, or `}`
>    |                              help: missing `,`
> 35 |     DuplicatedSheets,
>    |     ^^^^^^^^^^^^^^^^ unexpected token
> ```
> 

I may have misunderstood your intention, can you give me more information, like your code snippets, which could help me understand your needs better.

**Comment by mschnell1** [comment]
Something seems to have gone wrong with downloading the edit-xlsx code. 
I did another clean an compile and now it works. The erroneous word `result `is gone now. 
Sorry for trouble :(

**Comment by mschnell1** [comment]
Nonetheless I can't do 

```
#[derive(Debug)]
use std::num::ParseIntError;
use edit_xlsx::{Workbook, WorkbookResult, WorkbookError};
enum MyError {
    ParseIntError(ParseIntError),
    WorkbookError(WorkbookError),
}
```

I get: 
```
21 | use edit_xlsx::{Workbook, WorkbookResult, WorkbookError};
   |                                           ^^^^^^^^^^^^^ no `WorkbookError` in the root
```

**Comment by mschnell1** [comment]
Here a draft of the code I'd like to implement in my project:
```
                       let e_text = match e {
                           edit_xlsx::result::WorkbookError::FileNotFound  => "File not Found: ".to_owned() + &format!("{:?}", in_file_name),
                           _ => format!("{:?}", e),
                       };
  ``

**Comment by mschnell1** [comment]
``` Workbook::from_path(in_file_name)?;```

would be an even better option, if a conversion from `WorkbookError` into `std::io::Error` would be provided.

**Comment by mschnell1** [comment]
simply adding `pub use result::WorkbookError;` to `src/lib.rs` does the trick (temporarily)

**Comment by mschnell1** [comment]
Sorry I can't do what  is done in the `here` link given above.
